# Generated by Django 4.2.7 on 2023-12-17 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_review_customer_remove_wishlist_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
